# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HIaWB-PM7rTZrVkSBmhkw1E-Faed6akM
"""

import streamlit as st
import numpy as np

# --- Funciones de la Red Neuronal ---

def sigmoid(z):
    """Función de activación Sigmoide."""
    return 1 / (1 + np.exp(-z))

# --- ESTRUCTURA DE LA APLICACIÓN STREAMLIT ---

st.set_page_config(layout="wide")
st.title("🧠 Simulador Dinámico de Red Neuronal")
st.write("Define la arquitectura, y el simulador generará automáticamente los pesos, para que solo ingreses las variables X y obtengas el cálculo final.")

# --- BARRA LATERAL: CONFIGURACIÓN DINÁMICA DE LA ARQUITECTURA ---
st.sidebar.header("🎨 Configuración de la Red")

# 1. Entrada: Número de Variables X
num_inputs = st.sidebar.number_input("1. Número de Variables de Entrada (X):", min_value=1, max_value=10, value=2, step=1)
st.sidebar.markdown("---")

# 2. Capas Ocultas: Número de Capas
num_hidden_layers = st.sidebar.number_input("2. Número de Capas Ocultas:", min_value=1, max_value=5, value=2, step=1)
st.sidebar.markdown("---")

# 3. Neuronas por Capa
hidden_layers_neurons = []
for i in range(num_hidden_layers):
    # Usamos keys para que Streamlit sepa qué widget corresponde a cada capa
    neurons = st.sidebar.number_input(f"3. Neuronas en Capa Oculta {i+1}:", min_value=1, max_value=20, value=2, step=1, key=f'neurons_h{i+1}')
    hidden_layers_neurons.append(neurons)

num_outputs = 1
st.sidebar.markdown(f"**Salida:** {num_outputs} neurona (Fija)")

# --- INICIALIZACIÓN DE PESOS Y BIAS (ALEATORIOS Y AUTOMÁTICOS) ---
current_architecture = (num_inputs, tuple(hidden_layers_neurons), num_outputs)

# Se regeneran si la arquitectura cambia o si el usuario presiona el botón
if 'weights' not in st.session_state or 'biases' not in st.session_state or st.session_state.get('last_arch') != current_architecture or st.sidebar.button("Generar Nuevos Pesos y Bias Aleatorios"):

    st.session_state.weights = []
    st.session_state.biases = []
    st.session_state['last_arch'] = current_architecture # Guarda la arquitectura actual

    layer_sizes = [num_inputs] + hidden_layers_neurons + [num_outputs]

    # Generar W y b para cada conexión de capa
    for i in range(len(layer_sizes) - 1):
        # W (dimensión: (neuronas_previas, neuronas_actuales))
        st.session_state.weights.append(np.random.randn(layer_sizes[i], layer_sizes[i+1]) * 0.1)
        # b (dimensión: (neuronas_actuales))
        st.session_state.biases.append(np.random.randn(layer_sizes[i+1]) * 0.1)

weights = st.session_state.weights
biases = st.session_state.biases

# --- SECCIÓN PRINCIPAL: PESOS GENERADOS ---
st.subheader("⚙️ Parámetros Generados Automáticamente (Pesos W y Bias b)")
st.caption("Estos valores son generados aleatoriamente y basados en la arquitectura que definiste. Puedes ver las matrices y vectores, pero no se requiere que los ingreses.")

# Mostrar Pesos (W)
for i, w_matrix in enumerate(weights):
    st.markdown(f"##### Pesos W{i+1} (Matriz {w_matrix.shape})")
    st.dataframe(w_matrix.round(4), hide_index=True)

# Mostrar Bias (b)
for i, b_vector in enumerate(biases):
    st.markdown(f"##### Bias b{i+1} (Vector {b_vector.shape})")
    st.dataframe(b_vector.reshape(1, -1).round(4), hide_index=True) # Mostrar como fila

st.markdown("---")

# --- ENTRADAS X (ÚNICA ENTRADA DE TEXTO REQUERIDA) ---
st.subheader("➡️ 4. Variables de Entrada (X)")
st.warning("Este es el único campo de texto que DEBES ingresar o editar para hacer la predicción.")
default_X_str = ", ".join([f"{x:.4f}" for x in np.random.rand(num_inputs)])
input_X_str = st.text_input(f"Valores de X (Ingresa {num_inputs} valores separados por coma)", default_X_str, key="input_X_values")

X = None
try:
    X_list = [float(v.strip()) for v in input_X_str.split(',') if v.strip()]
    if len(X_list) != num_inputs:
        st.error(f"Debes ingresar exactamente {num_inputs} valores para X.")
    else:
        X = np.array(X_list)
except ValueError:
    st.error("Formato incorrecto para X. Usa números separados por comas.")

# --- CÁLCULO Y REPORTE ---
st.markdown("---")
if X is not None:
    if st.button("Calcular Predicción 🚀", key="calculate_btn"):
        st.header("📊 Reporte Final de la Propagación")
        current_activation = X

        # Propagación a través de las capas
        for i in range(len(weights)):
            layer_name = f"Capa Oculta {i+1}" if i < len(weights) - 1 else "Capa de Salida"
            st.subheader(f"✅ {layer_name}")

            input_for_layer = current_activation.reshape(1, -1)

            # Z = A_prev @ W + b
            Z = (input_for_layer @ weights[i]) + biases[i]

            # A = Sigmoid(Z)
            current_activation = sigmoid(Z.flatten())

            # Mostrar reporte
            col_w, col_b, col_z, col_a = st.columns(4)

            col_w.metric("Pesos W:", f"W{i+1} ({weights[i].shape})")
            with col_w.expander("Ver Matriz de Pesos W"):
                st.dataframe(weights[i].round(4), hide_index=True)

            col_b.metric("Bias b:", f"b{i+1} ({biases[i].shape})")
            with col_b.expander("Ver Vector de Bias b"):
                st.dataframe(biases[i].round(4).reshape(1, -1), hide_index=True)

            col_z.metric("Entrada Neta Z:", f"Z{i+1} ({Z.shape})")
            with col_z.expander("Ver Vector de Entrada Neta Z"):
                st.dataframe(Z.flatten().round(4).reshape(1, -1), hide_index=True)

            col_a.metric("Activación A:", f"A{i+1} ({current_activation.shape})")
            with col_a.expander("Ver Vector de Activación A"):
                st.dataframe(current_activation.round(4).reshape(1, -1), hide_index=True)


        final_output = current_activation[0]
        st.markdown("---")
        st.markdown("### ✨ Predicción Final de la Red Neuronal")
        st.success(f"**Salida Final (Predicción):** **{final_output:.4f}**")



